# Generated by Django 5.0.2 on 2024-04-13 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0005_savedrecipe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedrecipe", old_name="saved_at", new_name="saved_on",
        ),
        migrations.AlterField(
            model_name="savedrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_saved",
                to="myApp.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="savedrecipe",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
